---

- name: "SECTION | 17.1 | Account Logon"
  ansible.builtin.import_tasks:
    file: section_17.1.yml

- name: "SECTION | 17.2 | Account Management"
  ansible.builtin.import_tasks:
    file: section_17.2.yml

- name: "SECTION | 17.3 | Detailed Tracking"
  ansible.builtin.import_tasks:
    file: section_17.3.yml

- name: "SECTION | 17.4 | DS Access"
  ansible.builtin.import_tasks:
    file: section_17.4.yml

- name: "SECTION | 17.5 | Logon/Logoff"
  ansible.builtin.import_tasks:
    file: section_17.5.yml

- name: "SECTION | 17.6 | Object Access"
  ansible.builtin.import_tasks:
    file: section_17.6.yml

- name: "SECTION | 17.7 | Policy Change"
  ansible.builtin.import_tasks:
    file: section_17.7.yml

- name: "SECTION | 17.8 | Privilege Use"
  ansible.builtin.import_tasks:
    file: section_17.8.yml

- name: "SECTION | 17.9 | System"
  ansible.builtin.import_tasks:
    file: section_17.9.yml
