---

- name: "17.8.1 | PATCH | Ensure Audit Sensitive Privilege Use is set to Success and Failure"
  when: win22cis_rule_17_8_1
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_17.8.1
    - patch
    - NIST800-171_3.3.1
    - NIST800-171_3.3.2
    - NIST800-171_3.3.6
    - NIST800-53R5_AU-3
    - NIST800-53R5_AU-3_1
    - NIST800-53R5_AU-7
    - NIST800-53R5_AU-12
  block:
    - name: "17.8.1 | AUDIT | Ensure Audit Sensitive Privilege Use is set to Success and Failure | Get current audit events for Sensitive Privilege Use"
      ansible.windows.win_shell: AuditPol /get /subcategory:"{0cce9228-69ae-11d9-bed3-505054503030}" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      failed_when: false
      check_mode: false
      register: discovered_17_8_1_audit

    - name: "17.8.1 | PATCH | Ensure Audit Sensitive Privilege Use is set to Success and Failure | Enable Success for Sensitive Privilege Use"
      when: "'Success' not in discovered_17_8_1_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce9228-69ae-11d9-bed3-505054503030}" /success:enable

    - name: "17.8.1 | PATCH | Ensure Audit Sensitive Privilege Use is set to Success and Failure | Enable Failure for Sensitive Privilege Use"
      when: "'Failure' not in discovered_17_8_1_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"{0cce9228-69ae-11d9-bed3-505054503030}" /failure:enable
