---

- name: "18.10.41.1 | PATCH | Ensure Allow Message Service Cloud Sync is set to Disabled"
  when: win22cis_rule_18_10_41_1
  tags:
    - level2-domaincontroller
    - level2-memberserver
    - rule_18.10.41.1
    - patch
    - msc
    - NIST800-171_3.4.2
    - NIST800-171_3.4.6
    - NIST800-171_3.4.7
    - NIST800-53R5_CM-6
    - NIST800-53R5_CM-7
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Messaging
    name: AllowMessageSync
    data: 0
    type: dword
