---

- name: "18.10.56.1 | PATCH | (L2) Ensure 'Turn off Push To Install service' is set to 'Enabled'"
  when: win22cis_rule_18_10_56_1
  tags:
    - level2-domaincontroller
    - level2-memberserver
    - rule_18.10.56.1
    - patch
    - pushtoinstall
    - NIST800-171_3.4.8
    - NIST800-53R5_CM-7_5
    - NIST800-53R5_CM-10
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\PushToInstall
    name: DisablePushToInstall
    data: 1
    type: dword
