---

- name: "18.10.18.1 | PATCH | Ensure Enable App Installer is set to Disabled"
  when: win22cis_rule_18_10_18_1
  tags:
    - level2-domaincontroller
    - level2-memberserver
    - rule_18.10.18.1
    - patch
    - appinstaller
    - NIST800-171_3.4.2
    - NIST800-171_3.4.6
    - NIST800-171_3.4.7
    - NIST800-53R5_CM-6
    - NIST800-53R5_CM-7
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\AppInstaller
    name: EnableAppInstaller
    data: 0
    type: dword

- name: "18.10.18.2 | PATCH | Ensure Enable App Installer Experimental Features is set to Disabled"
  when: win22cis_rule_18_10_18_2
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_18.10.18.2
    - patch
    - appinstaller
    - NIST800-171_3.4.2
    - NIST800-171_3.4.6
    - NIST800-171_3.4.7
    - NIST800-53R5_CM-6
    - NIST800-53R5_CM-7
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\AppInstaller
    name: EnableExperimentalFeatures
    data: 0
    type: dword

- name: "18.10.18.3 | PATCH | Ensure Enable App Installer Hash Override is set to Disabled"
  when: win22cis_rule_18_10_18_3
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_18.10.18.3
    - patch
    - appinstaller
    - NIST800-171_3.4.2
    - NIST800-171_3.4.6
    - NIST800-171_3.4.7
    - NIST800-53R5_CM-6
    - NIST800-53R5_CM-7
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\AppInstaller
    name: EnableHashOverride
    data: 0
    type: dword

- name: "18.10.18.4 | PATCH | Ensure Enable App Installer Local Archive Malware Scan Override is set to Disabled"
  when: win22cis_rule_18_10_18_4
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_18.10.18.4
    - patch
    - appinstaller
    - NIST800-171_3.4.6
    - NIST800-171_3.4.7
    - NIST800-171_3.14.4
    - NIST800-171_3.14.5
    - NIST800-53R5_CM-6
    - NIST800-53R5_CM-7
    - NIST800-53R5_SI-3
    - NIST800-53R5_SI-4
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\AppInstaller
    name: EnableLocalArchiveMalwareScanOverride
    data: 0
    type: dword

- name: "18.10.18.5 | PATCH | Ensure Enable App Installer ms-appinstaller protocol is set to Disabled"
  when: win22cis_rule_18_10_18_5
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_18.10.18.5
    - patch
    - appinstaller
    - NIST800-171_3.4.2
    - NIST800-171_3.4.6
    - NIST800-171_3.4.7
    - NIST800-53R5_CM-6
    - NIST800-53R5_CM-7
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\AppInstaller
    name: EnableMSAppInstallerProtocol
    data: 0
    type: dword

- name: "18.10.18.6 | PATCH | Ensure Enable App Installer Microsoft Store Source Certificate Validation Bypass is set to Disabled"
  when: win22cis_rule_18_10_18_6
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_18.10.18.6
    - patch
    - appinstaller
    - NIST800-171_3.4.2
    - NIST800-171_3.4.6
    - NIST800-171_3.4.7
    - NIST800-53R5_CM-6
    - NIST800-53R5_CM-7
    - NIST800-53R5_SI-3
    - NIST800-53R5_SI-4
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\AppInstaller
    name: EnableBypassCertificatePinningForMicrosoftStore
    data: 0
    type: dword

- name: "18.10.18.7 | PATCH | Ensure Enable Windows Package Manager command line interfaces is set to Disabled"
  when: win22cis_rule_18_10_18_7
  tags:
    - level2-domaincontroller
    - level2-memberserver
    - rule_18.10.18.7
    - patch
    - appinstaller
    - NIST800-171_3.4.2
    - NIST800-171_3.4.6
    - NIST800-171_3.4.7
    - NIST800-53R5_CM-6
    - NIST800-53R5_CM-7
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\AppInstaller
    name: EnableWindowsPackageManagerCommandLineInterfaces
    data: 0
    type: dword
