---

- name: "18.10.14.1 | PATCH | Ensure Require pin for pairing is set to Enabled First Time OR Enabled Always"
  when: win22cis_rule_18_10_14_1
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - rule_18.10.14.1
    - automated
    - patch
    - pin
    - NIST800-171_3.5.2
    - NIST800-53R5_IA-5_c
  block:
    - name: "18.10.14.1 | PATCH | Ensure Require pin for pairing is set to Enabled First Time OR Enabled Always | Set Variable"
      when: win22cis_require_pin_for_pairing == 1 or win22cis_require_pin_for_pairing == 2
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Connect
        name: RequirePinForPairing
        data: "{{ win22cis_require_pin_for_pairing }}"
        type: dword

    - name: "18.10.14.1 | AUDIT | Ensure Require pin for pairing is set to Enabled First Time OR Enabled Always | Warning Check For Variable Standards"
      when:
        - win22cis_require_pin_for_pairing != 1
        - win22cis_require_pin_for_pairing != 2
      ansible.builtin.debug:
        msg:
          - "Warning!! You have an invalid setting for win22cis_require_pin_for_pairing. Please read"
          - "the notes for the variable and make the necessary change to the variable to be in compliance."

    - name: "18.10.14.1 | AUDIT | Ensure Require pin for pairing is set to Enabled First Time OR Enabled Always | Log a warning"
      when:
        - win22cis_require_pin_for_pairing != 1
        - win22cis_require_pin_for_pairing != 2
      vars:
        warn_control_id: '18.10.14.1'
      ansible.builtin.import_tasks:
        file: warning_facts.yml
