---

- name: "18.10.63.1 | PATCH | Ensure Turn off KMS Client Online AVS Validation is set to Enabled"
  when: win22cis_rule_18_10_63_1
  tags:
    - level2-domaincontroller
    - level2-memberserver
    - rule_18.10.63.1
    - patch
    - kms
    - NIST800-171_3.14.6
    - NIST800-171_3.14.7
    - NIST800-53R5_SI-4
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Nt\CurrentVersion\Software Protection Platform
    name: NoGenTicket
    data: 1
    type: dword
