---

- name: "18.8.1.1 | PATCH | Ensure Turn off notifications network usage is set to Enabled"
  when: win22cis_rule_18_8_1_1
  tags:
    - level2-domaincontroller
    - level2-memberserver
    - rule_18.8.1.1
    - patch
    - notifications
    - NIST800-171_3.14.6
    - NIST800-171_3.14.7
    - NIST800-53R5_SI-4
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\PushNotifications
    name: NoCloudApplicationNotification
    data: 1
    type: dword
