---

- name: "2.3.6.1 | PATCH | Ensure Domain member Digitally encrypt or sign secure channel data always is set to Enabled"
  when:
    - win22cis_rule_2_3_6_1
    - not prelim_win22cis_is_domain_controller
    - not prelim_win22cis_is_standalone
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - level1-domainmember
    - rule_2.3.6.1
    - patch
    - encryption
    - NIST800-171_3.1.13
    - NIST800-171_3.5.2
    - NIST800-171_3.13.8
    - NIST800-53R5_AC-17_2
    - NIST800-53R5_IA-5
    - NIST800-53R5_IA-5_1
    - NIST800-53R5_SC-8
    - NIST800-53R5_SC-8_1
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters
    name: RequireSignOrSeal
    data: 1
    type: dword

- name: "2.3.6.2 | PATCH | Ensure Domain member Digitally encrypt secure channel data when possible is set to Enabled"
  when:
    - win22cis_rule_2_3_6_2
    - not prelim_win22cis_is_domain_controller
    - not prelim_win22cis_is_standalone
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - level1-domainmember
    - rule_2.3.6.2
    - patch
    - encryption
    - NIST800-171_3.1.13
    - NIST800-171_3.5.2
    - NIST800-171_3.13.8
    - NIST800-53R5_AC-17_2
    - NIST800-53R5_IA-5
    - NIST800-53R5_IA-5_1
    - NIST800-53R5_SC-8
    - NIST800-53R5_SC-8_1
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters
    name: SealSecureChannel
    data: 1
    type: dword

- name: "2.3.6.3 | PATCH | Ensure Domain member Digitally sign secure channel data when possible is set to Enabled"
  when:
    - win22cis_rule_2_3_6_3
    - not prelim_win22cis_is_domain_controller
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - level1-domainmember
    - rule_2.3.6.3
    - patch
    - logon
    - NIST800-171_3.1.13
    - NIST800-171_3.5.2
    - NIST800-171_3.13.8
    - NIST800-53R5_AC-17_2
    - NIST800-53R5_IA-5
    - NIST800-53R5_IA-5_1
    - NIST800-53R5_SC-8
    - NIST800-53R5_SC-8_1
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters
    name: SignSecureChannel
    data: 1
    type: dword

- name: "2.3.6.4 | PATCH | Ensure Domain member Disable machine account password changes is set to Disabled"
  when:
    - win22cis_rule_2_3_6_4
    - not prelim_win22cis_is_domain_controller
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - level1-domainmember
    - rule_2.3.6.4
    - patch
    - logon
    - NIST800-171_3.1.1
    - NIST800-53R5_AC-2_1
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters
    name: DisablePasswordChange
    data: 0
    type: dword

- name: "2.3.6.5 | PATCH | Ensure Domain member Maximum machine account password age is set to 30 or fewer days but not 0"
  when:
    - win22cis_rule_2_3_6_5
    - not prelim_win22cis_is_domain_controller
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - level1-domainmember
    - rule_2.3.6.5
    - patch
    - account
    - NIST800-171_3.5.2
    - NIST800-53R5_IA-5_1
  block:
    - name: "2.3.6.5 | PATCH | Ensure Domain member Maximum machine account password age is set to 30 or fewer days but not 0 | Apply Settings To Registry"
      when:
        - win22cis_domain_member_maximum_password_age <= 30
        - win22cis_domain_member_maximum_password_age > 0
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters
        name: MaximumPasswordAge
        data: "{{ win22cis_domain_member_maximum_password_age }}"
        type: dword

    - name: "2.3.6.5 | AUDIT | Ensure Domain member Maximum machine account password age is set to 30 or fewer days but not 0 | Warning Check For Variable Standards"
      when: win22cis_domain_member_maximum_password_age > 30 or
          win22cis_domain_member_maximum_password_age == 0
      ansible.builtin.debug:
        msg:
          - "Warning!! You have an invalid number of days set for win22cis_domain_member_maximum_password_age please read"
          - "the notes for the variable and make the necessary change to the variable to be in compliance."

    - name: "2.3.6.5 | AUDIT | Ensure Domain member Maximum machine account password age is set to 30 or fewer days but not 0 | Warn Count"
      when: win22cis_domain_member_maximum_password_age > 30 or
          win22cis_domain_member_maximum_password_age == 0
      ansible.builtin.import_tasks:
        file: warning_facts.yml
      vars:
        warn_control_id: '2.3.6.5'

- name: "2.3.6.6 | PATCH | Ensure Domain member Require strong Windows 2000 or later session key is set to Enabled"
  when:
    - win22cis_rule_2_3_6_6
    - not prelim_win22cis_is_domain_controller
  tags:
    - level1-domaincontroller
    - level1-memberserver
    - level1-domainmember
    - rule_2.3.6.6
    - patch
    - logon
    - NIST800-171_3.1.13
    - NIST800-171_3.5.2
    - NIST800-171_3.13.8
    - NIST800-53R5_AC-17_2
    - NIST800-53R5_IA-5
    - NIST800-53R5_IA-5_1
    - NIST800-53R5_SC-8
    - NIST800-53R5_SC-8_1
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters
    name: RequireStrongKey
    data: 1
    type: dword
