prefix         = "github"
location       = "eastus"
tagname        = "ansible_lockdown"
system_size    = "Standard_D2s_v3"
OS_publisher   = "MicrosoftWindowsServer"
OS_version     = "2022"
system_release = "Datacenter-g2"
hostname       = "github"